version: "3.7"

services:
  web:
    image: nguyenkhacthanh/pastebin:latest
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASS=password
      - DB_NAME=pastebin
      - CACHE_TYPE=redis
      - CACHE_REDIS_HOST=redis
      - CACHE_REDIS_PASSWORD=
    ports:
      - 8000:80
    depends_on:
      - mysql
      - redis
    restart: on-failure
    networks:
      - mynet
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=pastebin
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    expose:
      - 3306
    ports:
      - 3306:3306
    restart: on-failure
    networks:
      - mynet
  redis:
    image: redis:latest
    expose:
      - 6379
    restart: on-failure
    networks:
      - mynet
networks:
  mynet:
