version: "3.7"

services:
  read:
    build:
      context: .
      dockerfile: read.Dockerfile
    environment:
      - DB_HOST=read-mysql
      - DB_USER=root
      - DB_PASS=password
      - DB_NAME=pastebin
      - CACHE_TYPE=redis
      - CACHE_REDIS_HOST=redis
      - CACHE_REDIS_PASSWORD=
    expose:
      - 80
    depends_on:
      - read-mysql
      - redis
    restart: on-failure
    networks:
      - mynet
  write:
    build:
      context: .
      dockerfile: write.Dockerfile
    environment:
      - DB_HOST=write-mysql
      - DB_USER=root
      - DB_PASS=password
      - DB_NAME=pastebin
    expose:
      - 80
    depends_on:
      - write-mysql
    restart: on-failure
    networks:
      - mynet
  write-mysql:   # master
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=pastebin
    volumes:
      - ./write-schema.sql:/docker-entrypoint-initdb.d/schema.sql
    expose:
      - 3306
    ports:
      - 3306:3306
    restart: on-failure
    networks:
      - mynet
  read-mysql:   # slave
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=pastebin
    volumes:
      - ./read-schema.sql:/docker-entrypoint-initdb.d/schema.sql
    expose:
      - 3306
    restart: on-failure
    depends_on:
      - write-mysql
    networks:
      - mynet
  redis:
    image: redis:latest
    expose:
      - 6379
    restart: on-failure
    networks:
      - mynet
  nginx:
    image: nginx:alpine
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - read
      - write
    networks:
      - mynet
networks:
  mynet:
