version: "3.7"

services:
  read-api:
    build:
      context: ./app/read
      dockerfile: Dockerfile
    environment:
      - DB_HOST=mysqlslave
      - DB_USER=root
      - DB_PASS=password
      - DB_NAME=pastebin
    expose:
      - 80
    depends_on:
      - mysqlslave
    restart: on-failure
    networks:
      - mynet
  write-api:
    build:
      context: ./app/write
      dockerfile: Dockerfile
    environment:
      - DB_HOST=mysqlmaster
      - DB_USER=root
      - DB_PASS=password
      - DB_NAME=pastebin
      - CELERY_BROKER_URL=amqp://root:password@rabbitmq:5672/celery
    expose:
      - 80
    command: /app/env/bin/gunicorn -k gevent -b 0.0.0.0:80 -w 2 app:app
    depends_on:
      - mysqlmaster
    restart: on-failure
    networks:
      - mynet
  write-async:
    build:
      context: ./app/write
      dockerfile: Dockerfile
    environment:
      - DB_HOST=mysqlmaster
      - DB_USER=root
      - DB_PASS=password
      - DB_NAME=pastebin
      - CELERY_BROKER_URL=amqp://root:password@rabbitmq:5672/celery
    expose:
      - 80
    depends_on:
      - mysqlmaster
    command: /app/env/bin/celery -A app.celery worker -l info
    restart: on-failure
    networks:
      - mynet
  flower:
    build:
      context: ./app/write
      dockerfile: Dockerfile
    environment:
      - CELERY_BROKER_URL=amqp://root:password@rabbitmq:5672/celery
      - BROKER_API=http://root:password@rabbitmq:15672/api/
    expose:
      - 5555
    ports:
      - 5555:5555
    depends_on:
      - rabbitmq
    command: /app/env/bin/celery -A app.celery flower --address=0.0.0.0 --port=5555 --broker_api=$${BROKER_API}
    restart: on-failure
    networks:
      - mynet
  mysqlmaster:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=pastebin
    volumes:
      - ./db/master/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./db/master/my.cnf:/etc/mysql/conf.d/mysql.cnf
    expose:
      - 3306
    ports:
      - 3306:3306
    restart: on-failure
    networks:
      - mynet
  mysqlslave:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=pastebin
    volumes:
      - ./db/slave/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./db/slave/my.cnf:/etc/mysql/conf.d/mysql.cnf
    expose:
      - 3306
    ports:
      - 3307:3306
    restart: on-failure
    networks:
      - mynet
  mysqlconfigure:
    image: mysql:5.7
    environment:
      - MYSQL_SLAVE_PASSWORD=password
      - MYSQL_MASTER_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_REPLICATION_USER=repl
      - MYSQL_REPLICATION_PASSWORD=repl
      - DELAY=60
    depends_on:
      - mysqlmaster
      - mysqlslave
    volumes:
      - ./db/setup.sh:/tmp/setup.sh
    command: /bin/bash -x /tmp/setup.sh
    networks:
      - mynet
  rabbitmq:
    image: rabbitmq:management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_DEFAULT_VHOST=celery
    expose:
      - 5672
      - 15672
    ports:
      - 15672:15672
    restart: on-failure
    networks:
      - mynet
  nginx:
    image: nginx:alpine
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - read-api
      - write-api
    networks:
      - mynet
networks:
  mynet:
